name: Run Unit Tests 

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Restore and build
        run: |
          dotnet restore
          dotnet build
        working-directory: ./Project

      - name: Run Unit Tests
        run: dotnet test
        working-directory: ./UnitTests